# Generated by Django 6.0.3 on 2026-03-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="joke",
            name="text",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
