# Generated by Django 6.0.2 on 2026-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField()),
                ("first_name", models.CharField()),
                ("ad_st_num", models.CharField()),
                ("ad_st_name", models.CharField()),
                ("ad_apt_num", models.CharField()),
                ("ad_zip_code", models.CharField()),
                ("dob", models.DateField()),
                ("do_reg", models.DateField()),
                ("part_af", models.CharField(max_length=2)),
                ("precint_num", models.CharField()),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
