# Generated by Django 6.0.2 on 2026-02-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("display_name", models.TextField()),
                ("profile_image_url", models.URLField(blank=True)),
                ("bio_text", models.TextField(blank=True)),
                ("join_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
