# Generated by Django 6.0.2 on 2026-02-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0002_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="photo",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
