# Generated by Django 6.0.2 on 2026-02-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0003_photo_image_file_alter_photo_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(),
        ),
    ]
