# Generated by Django 6.0.2 on 2026-02-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0004_alter_photo_image_url_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(),
        ),
    ]
