# Generated by Django 6.0.3 on 2026-04-08 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0009_alter_post_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="mini_insta.post",
            ),
        ),
    ]
